name       : beeref
version    : 0.2.0
release    : 3
source     :
    - https://github.com/rbreu/beeref/archive/refs/tags/v0.2.0.tar.gz : 3bd01e30ece5c845f6c39b452b608f6448540283ab81f0b05db8db1c4bf17fe0
homepage   : https://beeref.org/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : BeeRef Reference Image Viewer
description: |
    BeeRef lets you quickly arrange your reference images and view them while you create. Its minimal interface is designed not to get in the way of your creative process.
builddeps  :
    - python-exif
    - python-qt6
    - python-rectangle-packer
rundeps    :
    - python-exif
    - python-qt6
    - python-rectangle-packer
setup      : |
    %patch -p1 < $pkgfiles/make-type-conversions.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 $pkgfiles/beeref.desktop $installdir/usr/share/applications/beeref.desktop
    install -Dm00644 beeref/assets/logo.svg $installdir/usr/share/icons/hicolor/scalable/apps/beeref.svg
